(function() {var implementors = {
"rustc_const_eval":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"rustc_const_eval/const_eval/error/enum.ConstEvalErrKind.html\" title=\"enum rustc_const_eval::const_eval::error::ConstEvalErrKind\">ConstEvalErrKind</a>"]],
"rustc_driver":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"rustc_driver/args/enum.Error.html\" title=\"enum rustc_driver::args::Error\">Error</a>"]],
"rustc_error_messages":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"rustc_error_messages/enum.TranslationBundleError.html\" title=\"enum rustc_error_messages::TranslationBundleError\">TranslationBundleError</a>"]],
"rustc_errors":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"rustc_errors/struct.ExplicitBug.html\" title=\"struct rustc_errors::ExplicitBug\">ExplicitBug</a>"]],
"rustc_log":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"rustc_log/enum.Error.html\" title=\"enum rustc_log::Error\">Error</a>"]],
"rustc_span":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"rustc_span/fatal_error/struct.FatalError.html\" title=\"struct rustc_span::fatal_error::FatalError\">FatalError</a>"]],
"rustdoc":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"rustdoc/error/struct.Error.html\" title=\"struct rustdoc::error::Error\">Error</a>"]],
"rustfmt":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"rustfmt/enum.OperationError.html\" title=\"enum rustfmt::OperationError\">OperationError</a>"]],
"rustfmt_format_diff":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"rustfmt_format_diff/enum.FormatDiffError.html\" title=\"enum rustfmt_format_diff::FormatDiffError\">FormatDiffError</a>"]],
"rustfmt_nightly":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"rustfmt_nightly/config/file_lines/enum.FileLinesError.html\" title=\"enum rustfmt_nightly::config::file_lines::FileLinesError\">FileLinesError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"rustfmt_nightly/config/struct.ToTomlError.html\" title=\"struct rustfmt_nightly::config::ToTomlError\">ToTomlError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"rustfmt_nightly/modules/struct.ModuleResolutionError.html\" title=\"struct rustfmt_nightly::modules::ModuleResolutionError\">ModuleResolutionError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"rustfmt_nightly/modules/enum.ModuleResolutionErrorKind.html\" title=\"enum rustfmt_nightly::modules::ModuleResolutionErrorKind\">ModuleResolutionErrorKind</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"rustfmt_nightly/enum.ErrorKind.html\" title=\"enum rustfmt_nightly::ErrorKind\">ErrorKind</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()